language: java

jdk:
  - openjdk8

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.npm-cache"

before_install:
  - npm config set cache "$HOME/.npm-cache"

script:
  - mvn surefire:test
  - mvn spring-boot:run -Pdevelop -Dspring.profiles.active=local
